language: php

branches:
  except:
    - build

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: hhvm

sudo: false

before_script:
  - npm install
  - npm install -g karma-cli
  - composer install

script:
  - npm test
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

cache:
  directories:
    - "$HOME/.composer/cache/files"
    - node_modules

git:
  depth: 5
