blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://directus.chat/
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://docs.directus.io/
    about: Have a look at our documentation.
