# This composer file spins up the databases, and a copy of Directus per database
#
# ONLY FOR RUNNING TESTS. THIS IS NOT INTENDED FOR PRODUCTION OR DEVELOPMENT USE.
#
# Ports:
#   Postgres:        5100
#   MySQL:           5101
#   MariaDB:         5102
#   MS SQL:          5103
#   Oracle:          5104
#
# Credentials:
#   Postgres:
#     User:          postgres
#     Password:      secret
#
#   MySQL:
#     User:          root
#     Password:      secret
#
#   MariaDB:
#     User:          root
#     Password:      secret
#
#   MS SQL:
#     User:          sa
#     Password:      Test@123
#
#   Oracle DB:
#     User:          secretsysuser
#     Password:      secretpassword
#     Role:          SYSDEFAULT
#     SID:           XE

version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: directus
    ports:
      - 5100:5432
    healthcheck:
      test: ['CMD-SHELL', '/usr/local/bin/psql "postgres://postgres:secret@postgres/directus" -c "SELECT 1"']
      interval: 10s
      timeout: 5s
      retries: 5
      start-period: 10s

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: directus
    ports:
      - 5101:3306
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/mysql -hlocalhost -uroot -psecret -e "SELECT 1"']
      interval: 10s
      timeout: 5s
      retries: 5
      start-period: 10s

  maria:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: directus
    ports:
      - 5102:3306
    healthcheck:
      test: ['CMD-SHELL', '/usr/bin/mysql -hlocalhost -uroot -psecret -e "SELECT 1"']
      interval: 10s
      timeout: 5s
      retries: 5
      start-period: 10s

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123
    ports:
      - 5103:1433
    healthcheck:
      test: ['CMD-SHELL', '/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Test@123 -Q "select 1"']
      interval: 10s
      timeout: 5s
      retries: 5
      start-period: 10s

  oracle:
    image: quillbuilduser/oracle-18-xe-micro-sq
    ports:
      - 5104:1521
    environment:
      - OPATCH_JRE_MEMORY_OPTIONS=-Xms128m -Xmx256m -XX:PermSize=16m -XX:MaxPermSize=32m -Xss1m
      - ORACLE_ALLOW_REMOTE=true
    shm_size: '1gb' # more like smh-size ammirite 🥁
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/opt/oracle/product/18c/dbhomeXE/bin/sqlplus / as SYSDBA <<< "SELECT 13376411 FROM DUAL; exit;" | grep
          "13376411";',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start-period: 10s

volumes:
  mysql_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
