[build.environment]
	NODE_VERSION = "18"

[build]
	publish = ".vitepress/dist"
	command = "pnpm run build"

[dev]
	command = "pnpm run dev"
	targetPort = 5173
	autoLaunch = false
	framework = "#custom"


[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

[[redirects]]
	from = "/configuration/*"
	to = "/app/:splat"
	status = 301

[[redirects]]
	from = "/cookbook/*"
	to = "/guides/:splat"
	status = 301

[[redirects]]
	from = "/guides/flows/trigger-static-site-build-*"
	to = "/guides/headless-cms/trigger-static-builds/:splat"
	status = 301

[[redirects]]
	from = "/guides/data-models/personal-portfolio-using-m2a"
	to = "/"
	status = 301

[[redirects]]
	from = "/guides/data-models/build-a-content-hierarchy"
	to = "/"
	status = 301

[[redirects]]
	from = "/guides/permissions/basic-workflows"
	to = "/guides/headless-cms/approval-workflows"
	status = 301

[[redirects]]
	from = "/use-cases/headless-cms/build-website-*"
	to = "/guides/headless-cms/build-static-website/:splat"
	status = 301
	
[[redirects]]
	from = "/use-cases/headless-cms/create-reusable-page-components-using-m2a"
	to = "/guides/headless-cms/reusable-components"
	status = 301

[[redirects]]
	from = "/cloud/*"
	to = "/"
	status = 301

[[redirects]]
	from = "/getting-started/backing-directus"
	to = "/contributing/sponsor"
	status = 301

[[redirects]]
	from = "/app/content/*"
	to = "/user-guide/content-module/content/:splat"
	status = 301

[[redirects]]
  from = "/app/users-roles-permissions"
  to = "/user-guide/user-management/users-roles-permissions"
  status = 301

[[redirects]]
  from = "/getting-started/glossary"
  to = "/user-guide/overview/glossary"
  status = 301

[[redirects]]
  from = "/app/activity-log"
  to = "/user-guide/settings/activity-log"
  status = 301

[[redirects]]
  from = "/app/insights"
  to = "/user-guide/insights/dashboards"
  status = 301

[[redirects]]
  from = "/app/file-library"
  to = "/user-guide/file-library/files"
  status = 301

[[redirects]]
  from = "/app/project-settings"
  to = "/user-guide/cloud/project-settings"
  status = 301

[[redirects]]
  from = "/app/content/shares"
  to = "/user-guide/content-module/content/shares"
  status = 301

[[redirects]]
  from = "/app/user-directory"
  to = "/user-guide/user-management/user-directory"
  status = 301

[[redirects]]
	from = "/cloud/*"
	to = "/user-guide/cloud/:splat"
	status = 301