[build.environment]
	NODE_VERSION = "18"

[build]
	publish = ".vitepress/dist"
	command = "pnpm run build"

[dev]
	command = "pnpm run dev"
	targetPort = 5173
	autoLaunch = false
	framework = "#custom"

[[redirects]]
	from = "/"
	to = "/getting-started/introduction"
	status = 301
	force = true

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

[[redirects]]
	from = "/configuration/*"
	to = "/app/:splat"
	status = 301

[[redirects]]
	from = "/cookbook/*"
	to = "/guides/:splat"
	status = 301

[[redirects]]
	from = "/guides/flows/trigger-static-site-build-*"
	to = "/guides/headless-cms/trigger-static-builds/:splat"
	status = 301