name: Add label to issue

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@v1
        with:
          add-labels: 'Bug (Potential)'
