name: Blackbox Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - tests/blackbox/**
      - packages/**
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/blackbox-pr.yml

concurrency:
  group: blackbox-pr-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  test:
    name: ${{ matrix.vendor }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vendor:
          - mysql
          - mysql5
          - maria
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Install mysql2
        run: pnpm --filter api add -O -E mysql2

      - name: Start services
        run:
          docker compose -f tests/blackbox/docker-compose.yml up ${{ matrix.vendor }} auth-saml redis minio minio-mc -d
          --quiet-pull --wait

      - name: Run tests
        run: TEST_DB=${{ matrix.vendor }} pnpm run test:blackbox
