name: Blackbox Tests

on:
  push:
    branches:
      - main
      - next
    paths:
      - api/**
      - tests/blackbox/**
      - packages/**
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/blackbox-main.yml
  pull_request:
    branches:
      - main

concurrency:
  group: blackbox-main-vitest
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  test:
    name: ${{ matrix.vendor }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vendor:
          - sqlite3
          - postgres
          - postgres10
          - mysql
          - mysql5
          - maria
          - mssql
          - oracle
          - cockroachdb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Install Oracle client
        if: matrix.vendor == 'oracle'
        run: |
          sudo apt update -y && sudo apt install -y alien libaio1 && \
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/$ORACLE_DL && \
          sudo alien -i $ORACLE_DL && \
          pnpm -w -D add oracledb@5
        env:
          ORACLE_DL: oracle-instantclient-basic-21.4.0.0.0-1.el8.x86_64.rpm

      - name: Start MSSQL
        if: matrix.vendor == 'mssql'
        run: |
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-preview.list | sudo tee /etc/apt/sources.list.d/mssql-server-preview.list
          sudo apt-get update
          sudo apt-get install -y mssql-server
          sudo MSSQL_PID='express' MSSQL_SA_PASSWORD='Test@123' /opt/mssql/bin/mssql-conf -n setup accept-eula
          sudo /opt/mssql/bin/mssql-conf set network.tcpport 6105
          sudo systemctl restart mssql-server

          docker compose -f tests/blackbox/docker-compose.yml up auth-saml redis minio minio-mc -d --quiet-pull --wait

      - name: Start ${{ matrix.vendor }}
        if: matrix.vendor != 'sqlite3' && matrix.vendor != 'mssql'
        run: docker compose -f tests/blackbox/docker-compose.yml up ${{ matrix.vendor }} -d --quiet-pull --wait

      - name: Start services
        run:
          docker compose -f tests/blackbox/docker-compose.yml up auth-saml redis minio minio-mc -d --quiet-pull --wait

      - name: Run tests
        run: TEST_DB=${{ matrix.vendor }} pnpm run test:blackbox
