name: E2E

on:
  push:
    branches:
      - main

jobs:
  # Skip subsequent jobs if changed files are out of scope for this workflow
  pre_check:
    name: Pre Check
    runs-on: ubuntu-latest
    outputs:
      # Returns true when only the files listed below have changed
      skip: ${{ steps.changed_files.outputs.only_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Fetch whole history on push events (required for comparison)
          fetch-depth: ${{ github.event_name == 'push' && '0' || '1' }}

      - name: Check Changed Files
        id: changed_files
        uses: tj-actions/changed-files@v10.1
        with:
          files: |
            app/src/lang/translations/*.yaml

  tests:
    name: Tests
    needs: pre_check
    if: needs.pre_check.outputs.skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db:
          - mssql
          - mysql
          - postgres
          - maria
          # - sqlite
        node-version:
          # - 12-alpine
          # - 14-alpine
          - 16-alpine
    env:
      CACHED_IMAGE: ghcr.io/directus/directus-e2e-test-cache:${{ matrix.node-version }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Cached Directus Image
        run: |
          docker pull $CACHED_IMAGE || true
          docker tag $CACHED_IMAGE directus-test-image || true

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Run Tests
        env:
          TEST_NODE_VERSION: ${{ matrix.node-version }}
          TEST_DB: ${{ matrix.db }}
        run: npm run test:e2e

      - name: Push Cached Image
        # Only push the new cache image on the main branch once per node version
        if: github.ref == 'refs/heads/main' && github.repository == 'directus/directus' && matrix.db == 'sqlite3'
        run: |
          docker tag directus-test-image $CACHED_IMAGE
          docker push $CACHED_IMAGE || true
