name: Lint

on:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  lint:
    name: Lint
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run linters
        run: pnpm run lint
