name: 'Build'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: npm

    - name: Cache built repository
      id: build
      uses: actions/cache@v2
      with:
        path: './'
        key: ${{ github.sha }}

    - name: Build repository
      if: steps.build.outputs.cache-hit != 'true'
      run: npm ci && npm run build
