name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Skip subsequent jobs if changed files are out of scope for this workflow
  pre_check:
    name: Pre Check
    runs-on: ubuntu-latest
    outputs:
      # Returns true when only the files listed below have changed
      skip: ${{ steps.changed_files.outputs.only_changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Fetch whole history on push events (required for comparison)
          fetch-depth: ${{ github.event_name == 'push' && '0' || '1' }}

      - name: Check Changed Files
        id: changed_files
        uses: tj-actions/changed-files@v10.1
        with:
          files: |
            app/src/lang/translations/*.yaml

  test:
    name: Node ${{ matrix.node }}
    needs: pre_check
    if: needs.pre_check.outputs.skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '16'
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Packages
        run: npm run build

      - name: Run Tests
        run: npm run test
        env:
          SECRET: TEST_SECRET
